name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  actions: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
